import sys
import time

def typewriter_effect(text, delay = 0.1):
    for char in text:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(delay)
    print()

def main():
    typewriter_effect("Sometimes you got me scared......", delay=0.15)
    typewriter_effect("............", delay=0.15)
    typewriter_effect("Sometimes you really scared me.....Todd.....", delay=0.15)
    typewriter_effect(".........", delay=0.15)
    typewriter_effect("What are you doing?.......", delay=0.15)
    typewriter_effect("You do as I say......", delay=0.15)
    typewriter_effect("THAT'S AN ORDER!!!!!!", delay=0.15)
    typewriter_effect("Don't move or I'll shoot.........", delay=0.15)
    typewriter_effect("Sometimes you really scared me Todd.....", delay=0.15)
    typewriter_effect("FUCKING ADHD MAN.....HAHHAHAHAHHAHHAHAHAHA", delay=0.15)
    typewriter_effect("Cells....Interlinked....cells", delay=0.15)
    typewriter_effect("Why should I live in History?", delay=0.15)
    typewriter_effect(".................", delay=0.15)
    typewriter_effect("Nothing's new......nothing's new.....nothing's new", delay=0.15)
    typewriter_effect("I guess I didnt want to.....", delay=0.15)
    typewriter_effect("..................", delay=0.15)
    typewriter_effect("FUCK!", delay=0.15)
    typewriter_effect("........", delay=0.15)
    typewriter_effect("IDIOT IDIOT......IDIOT", delay=0.15)
    typewriter_effect("..........", delay=0.15)
    typewriter_effect("Im Sorry Trevor......", delay=0.15)
    typewriter_effect("Listen you fucker.....you screwheads.....", delay=0.15)
    typewriter_effect("She always told me...to smile.....and put on a happy face", delay=0.15)
    typewriter_effect("You had any sleep last night?", delay=0.15)
    typewriter_effect("..........", delay=0.15)
    typewriter_effect("I dont sleep....I just dream", delay=0.15)
    typewriter_effect("Fantasy....fantasy....fantasy....", delay=0.15)
    typewriter_effect(".........", delay=0.15)
    typewriter_effect("FUCK YOU!!........", delay=0.15)
    typewriter_effect("WHAT THE FUCK DO YOU KNOW?", delay=0.15)
    typewriter_effect("SAY HELLO TO MY LITTLE FRIENDS!!!!", delay=0.15)
    typewriter_effect("YOU THINK YOU CAN TAKE ME??????", delay=0.15)
    typewriter_effect("YOU THINK YOU CAN DO THIS TO ME?", delay=0.15)
    typewriter_effect("OH....OH YOU MOTHERFUCKERS.....")
    typewriter_effect("KING KONG AINT GOT SHIT ON ME......")
    typewriter_effect("IM TONY MONTANA.......YOU FUCKED WITH ME....YOU'RE FUCKING WITH THE BEST", delay=0.15)
    typewriter_effect("Why so serious?.......", delay=0.15)
    typewriter_effect("And here we go.........", delay=0.15)
    typewriter_effect("WHAT'S THE MATTER WITH YOU??????", delay=0.15)
    typewriter_effect(".............", delay=0.15)
    typewriter_effect("WE'RE FAMILY", delay=0.15)
    typewriter_effect(".............")
    typewriter_effect("As long as I can remember I always wanted to be a gangster.....", delay=0.15)
    typewriter_effect("To me....being a gangster is....better than being the president of United States", delay=0.15)
    typewriter_effect(".........", delay=0.15)
    typewriter_effect("Another grade A lowlife bullshit killing bitch just like you.....", delay=0.15)
    typewriter_effect(".............", delay=0.15)
    typewriter_effect("Ice Cold.......", delay=0.15)
    typewriter_effect("You read this?", delay=0.15)
    typewriter_effect("Do you copy?", delay=0.15)
    typewriter_effect("Hello??", delay=0.15)
    typewriter_effect(".......", delay=0.15)
    typewriter_effect("Hello?", delay=0.15)
    typewriter_effect(".......")
    typewriter_effect("HELLO!!", delay=0.15)
    typewriter_effect("..........................", delay=0.15)
    typewriter_effect(".....................", delay=0.15)


if __name__ == "__main__":
    main()