import sys
import time

def typewriter_effect(text, delay = 0.18):
    for char in text:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(delay)
    sys.stdout.write("\n")

    
def main():
    typewriter_effect("Talk about cohle....he's...a strange guy isnt he?", delay=0.18)
    typewriter_effect("........", delay=0.18)
    typewriter_effect("Strange...yeah", delay=0.18)
    typewriter_effect("Rust will pick up a fight with the sky....If he doesnt see the blue color", delay=0.18)
    typewriter_effect("Talk about.....Dora Lang.....The Yellow King", delay=0.18)
    typewriter_effect("...........", delay=0.18)
    typewriter_effect("January 3rd....my daughter's birthday", delay=0.18)
    typewriter_effect("I think human consiusness...is a tragic mistep of evolutions", delay=0.18)
    typewriter_effect("We're the creature that should not be exist.....by natural law", delay=0.18)
    typewriter_effect(".........", delay=0.18)
    typewriter_effect("Well...he wasnt exactly the boogeyman....", delay=0.18)
    typewriter_effect("He was the one you actually send to kill the fucking boogeyman", delay=0.18)
    typewriter_effect("He's a man of focus....commitment....and sheer fucking will", delay=0.18)
    typewriter_effect("...........", delay=0.18)
    typewriter_effect("Something that you dont have inside you....", delay=0.18)
    typewriter_effect("You say we were locked and loaded?", delay=0.18)
    typewriter_effect("Are you cooperating?", delay=0.18)
    typewriter_effect("..........", delay=0.18)
    typewriter_effect("Look at my eyes sir....you tell me", delay=0.18)
    typewriter_effect("If you dont fight....you'll die", delay=0.18)
    typewriter_effect("Rest in peace.....", delay=0.18)
    typewriter_effect("........", delay=0.18)
    typewriter_effect("I Saw you with the box what was in the box???", delay=0.18)
    typewriter_effect("WHAT'S IN THE FUCKING BOX?", delay=0.18)
    typewriter_effect("Oh....he didnt know", delay=0.18)
    typewriter_effect("Do you hear me detective?", delay=0.18)
    typewriter_effect("Im trying to admire your work....and your pretty wife...", delay=0.18)
    typewriter_effect(".....Tracey.....", delay=0.18)
    typewriter_effect("...........", delay=0.18)
    typewriter_effect("All hands in hands walk into extinction", delay=0.18)
    typewriter_effect(".........", delay=0.18)
    typewriter_effect("You got any sleep last night?", delay=0.18)
    typewriter_effect("Giant gutter space.......", delay=0.18)
    typewriter_effect("You wonder ever....if you're a bad man?", delay=0.18)
    typewriter_effect("I can be hard to live with.....", delay=0.18)
    typewriter_effect("Sometimes I just....not good for people", delay=0.18)
    typewriter_effect("And sometimes its not good fot them", delay=0.18)
    typewriter_effect("No...I dont wonder Marty....world needs bad man", delay=0.18)
    typewriter_effect("We keep the other bad man from the door....", delay=0.18)
    typewriter_effect("I dont sleep...I just dream", delay=0.18)
    typewriter_effect("...........")
    typewriter_effect("Dora Lang....Carcosa.....The Yellow King")
    typewriter_effect("All hands in hands walks into extinction", delay=0.18)
    typewriter_effect("Nature creates a species that should not be exist....by natural law", delay=0.18)

if __name__ == "__main__":
    main()